version: "3.9"

services:
  db:
    image: postgres:16.1-alpine
    restart: always
    env_file: postgres_secrets.env
    ports:
      - "5434:5434"
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: postgres_secrets.env
    ports:
      - "7070:80"
volumes:
  db:
    driver: local
